// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAmwRg5WhczP-I67X2RGLwqPlvJFlGmSg',
    appId: '1:572722200852:web:91c588f388d3498b2b4201',
    messagingSenderId: '572722200852',
    projectId: 'flutter37hrdemo',
    authDomain: 'flutter37hrdemo.firebaseapp.com',
    storageBucket: 'flutter37hrdemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFwZE-nGmXTfc91xbPlmOidUxT8wFcrlI',
    appId: '1:572722200852:android:ce92c1261a0b90592b4201',
    messagingSenderId: '572722200852',
    projectId: 'flutter37hrdemo',
    storageBucket: 'flutter37hrdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8MqmTfSETz-g6A8ZVufXGsqwo01EM0x4',
    appId: '1:572722200852:ios:ea802e06f9c559422b4201',
    messagingSenderId: '572722200852',
    projectId: 'flutter37hrdemo',
    storageBucket: 'flutter37hrdemo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8MqmTfSETz-g6A8ZVufXGsqwo01EM0x4',
    appId: '1:572722200852:ios:ea802e06f9c559422b4201',
    messagingSenderId: '572722200852',
    projectId: 'flutter37hrdemo',
    storageBucket: 'flutter37hrdemo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAmwRg5WhczP-I67X2RGLwqPlvJFlGmSg',
    appId: '1:572722200852:web:209a8ef777cce8592b4201',
    messagingSenderId: '572722200852',
    projectId: 'flutter37hrdemo',
    authDomain: 'flutter37hrdemo.firebaseapp.com',
    storageBucket: 'flutter37hrdemo.appspot.com',
  );
}
